services:
  - type: web
    name: pmecompta-backend
    runtime: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FRONTEND_URL
        value: https://hackverse-brainstorm.vercel.app
      - key: DATABASE_URL
        value: postgresql://pme_user:6rp9nib6evfMfeowoJEYbX1wxmH3zEU5@dpg-d7mh81a8qa3s739nkfjg-a.ohio-postgres.render.com/pme_compta
      - key: CORS_ALLOW_ORIGIN_REGEX
        value: https://.*\.vercel\.app
